In [18]:
import numpy as np
# 多次元配列の作成
array1 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
array2 = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

# 行列演算
# 行列の積
multiplication = np.dot(array1, array2)
print("\n行列の積の結果:")
print(multiplication)

# 最大値を求める
max = np.max(multiplication)
print("加算結果の最大値:", max)


行列の積の結果:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
加算結果の最大値: 138
