In [18]:
import numpy as np

# 多次元配列の作成
array1 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

array2 = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

# 行列演算
# 行列の加算
addition = array1 + array2
print("行列の加算結果:")
print(addition)

# 最大値を求める
max = np.max(addition)
print("最大値:", max)

行列の加算結果:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
最大値: 10
